language: android
sudo: false
android:
  components:
  - android-28
  - build-tools-28.0.3
  - sys-img-armeabi-v7a-android-24

script:
- echo "starting script"
  - ./gradlew clean build

# Emulator Management: Create, Start and Wait
before_script:
- echo "Starting emulator"
- echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- adb shell input keyevent 82 &
- echo "starting test"
- ./gradlew connectedCheck
- ./gradlew connectedAndroidTest createDebugCoverageReport coveralls